{% set name = "placekey" %}
{% set version = "0.0.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/placekey-{{ version }}.tar.gz
  sha256: 39bf744a26795f25b6a953fa97eef0d9e070b1af350e061e99550735951f5549

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - backoff
    - h3-py
    - python >={{ python_min }}
    - ratelimit
    - requests
    - shapely

test:
  imports:
    - placekey
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Placekey/placekey-py
  summary: Utilities for working with Placekeys
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ecmascriptguru
